server:
  port: 9002
spring:
  application:
    name: microservice-user
  profiles:
    active: prod

  datasource:
    url: jdbc:mysql://10.16.32.172:3307/springcloud?userUnicode=true&characterEncoding=UTF8&useSSL=false&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true  #是否打印sql语句
    generate-ddl: true  #是否自动建表
    database: mysql  #数据库类型
eureka:
  client:
    fetch-registry: true  #作为客户端需要从eureka获取信息
    register-with-eureka: true  #作为客户端注册到eureka
    service-url: #客户端注册地址
      defaultZone: http://10.16.32.213:8888/eureka,http://10.16.32.212:8888/eureka
  instance:
    prefer-ip-address: true  #优先使用该服务的IP地址注册到eureka，在生产环境建议改为true
